apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: apiserver
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: apiserver
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: apiserver
  name: apiserver
spec:
  containers:
  - image: avijitmajumder/python-apiserver:v1
    name: apiserver
    ports:
    - containerPort: 5000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
