apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: webclient
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31004
  type: NodePort
  selector:
    app: web-frontend
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web-frontend
  name: webclient
spec:
  containers:
  - image: avijitmajumder/python-gethostwebapi:v4
    name: webclient
    ports:
    - containerPort: 5000
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
